force-app/main/default/objects/POS_Error_Log__c/POS_Error_Log__c.object-meta.xml
<CustomObject>
    <label>POS Error Log</label>
    <nameField>
        <label>POS Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POS Errors Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/POS_Error_Log__c/fields/Error_Line__c.field-meta.xml
<CustomField>
    <fullName>Error_Line__c</fullName>
    <label>Error Line</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POS_Error_Log__c/fields/Exception_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type_Name__c</fullName>
    <label>Exception Type Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Error Handler/LightspeedPOSErrorControllerTest.cls
@isTest
public class LightspeedPOSErrorControllerTest {
    @isTest
    static void testGetErrors(){
        POS_Error_Log__c errorLog = new POS_Error_Log__c(
					Name = 'Test Error Log',
					Exception_Type_Name__c = 'System.NullPointerException',
					StackTrace__c = 'null input to JSON parser , (System Code) Class.LightspeedSaleRESTService.handleHookSales: line 27, column 1',
                    Error_Line__c = 'Line: 15'
					);
		insert errorLog;

        LightspeedPOSErrorHandlerController.GetErrors();
    }
}