force-app/main/default/objects/POS_Error_Log__c/POS_Error_Log__c.object-meta.xml
<CustomObject>
    <label>POS Error Log</label>
    <nameField>
        <label>POS Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POS Errors Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/POS_Error_Log__c/fields/Error_Line__c.field-meta.xml
<CustomField>
    <fullName>Error_Line__c</fullName>
    <label>Error Line</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POS_Error_Log__c/fields/Exception_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type_Name__c</fullName>
    <label>Exception Type Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POS_Error_Log__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Error Handler/LightspeedPOSErrorHandler.cls
public class LightspeedPOSErrorHandler{

	public static void insertErrorLog(Exception ex) {
		try {
			String userId = UserInfo.getUserId();
			POS_Error_Log__c error = new POS_Error_Log__c(
				User_Id__c = userId,
				name = ex.getMessage().left(80),
				Exception_Type_Name__c = ex.getTypeName(),
				Error_Line__c = 'Line: ' + ex.getLineNumber(),
				StackTrace__c = ex.getMessage() + ' , ' + ex.getStackTraceString()
			);
			insert error;
		} catch(Exception e) {
			insertErrorLog(e);
		}
	}
}